apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: filosofi-app

resources:
  - ../../base

images:
  - name: ghcr.io/z20ben/filosofi-yogya-mod
    newTag: latest  # Will be updated by CI

replicas:
  - name: filosofi-yogya
    count: 2
