apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: filosofi-app

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: filosofi-yogya
  managed-by: argocd
